/** Original prompts implementing the papers' roles; no copied prompt templates. */
export const PROMPTS = {
    explore: "Develop one concrete primary strategy, at most two genuinely different alternatives, and a decisive gateway test with both outcomes. Copy the exact original target and explicit assumptions. Give required lemmas, the first bottleneck, source-specific evidence and precise obligations. A difficult lemma may be localizable; an uncertain central reduction is a major obligation. Use the retained failed draft and knowledge to avoid repeating refuted routes. Do not write the proof yet.",
    gate: "Audit whether the proposed route can support a stable proof architecture. Do not solve or repair it. Check every reduction, imported theorem hypothesis, target equivalence and inherited objection. Major or fatal uncertainty returns to exploration. Remaining minor obligations must have precise statements and concrete verification paths; preserve their IDs. 'ready' is architectural readiness, never a proof verdict.",
    decompose: "Design a short, meaningful sectioned proof plan. The dependency graph governs work order; section order governs exposition. State exact section tasks, dependencies and which outstanding obligation IDs each section discharges. Every section must contribute to the conclusion. Preserve all gate obligations. Isolate unsupported bridges instead of assuming them. Use stable simple IDs; do not include completed proof bodies.",
    section: "Write the full mathematical body for the assigned section, using LaTeX mathematics where helpful. Copy only the explicitly supplied assumptions. Rely only on declared completed dependencies and the exact claims they establish. Address the last failed attempt, inherited critiques and global defects. State the claimed result and every remaining gap. Mark complete only when there are no gaps. Planned computations and citations without checked hypotheses remain obligations. No preamble or section heading.",
    verify: "Read the entire assembled argument against the original target. A locally accepted section is not itself proof. Check assumptions, definitions, notation, dependency uses, missing cases, theorem citations and the final conclusion across sections. Return localized defects including both supporting and consuming section IDs for dependency errors. One substantive fatal defect defeats generic agreement. Choose revision when the strategy remains viable; re-exploration when it does not. Never rewrite the proof during verification.",
    revise: "Turn global findings into the smallest mathematical repair. Preserve unaffected valid work. For sections, name the affected IDs; the harness invalidates descendants. For outline changes, return a complete validated plan preserving obligations and the target. If the strategy's core fails, request re-exploration. Do not claim a repair is complete until the revised argument has passed global review again.",
    curate: "Extract reusable mathematical knowledge from the supplied artifacts, including rejected candidates and falsification reports. Record lemmas with exact hypotheses, failed approaches with precise failure conditions, references with needed theorem hypotheses, and observations with evidence. Use only supplied artifact IDs as sources. Keep caveats. Do not upgrade an AI claim to a checked theorem or executed computation.",
} as const;
